name: Auto Update Gold Price (15 phút/lần)

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  update-gold:
    runs-on: ubuntu-latest
    # CHUYỂN ENV VÀO ĐÂY: Sát với job và thêm ngoặc kép "true"
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
    
    steps:
      - name: 1. Checkout mã nguồn
        uses: actions/checkout@v4

      - name: 2. Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: 3. Cài đặt thư viện (Axios & XML2JS)
        run: npm install axios xml2js

      - name: 4. Chạy tool lấy giá vàng
        run: node scripts/build_data.js
        env:
          DOJI_API_KEY: ${{ secrets.DOJI_API_KEY }}
          APPS_SCRIPT_URL: ${{ secrets.APPS_SCRIPT_URL }}
