name: Inject Secrets Into HTML

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Inject secrets into HTML
        run: |
          sed -i "s|const API_KEY = \"GH_API_KEY\";|const API_KEY = '${{ secrets.GH_API_KEY }}';|g" index.html
          sed -i "s|const FILE_PATH = \"GH_FILE_PATH\";|const FILE_PATH = '${{ secrets.GH_FILE_PATH }}';|g" index.html
          sed -i "s|const FOLDER_ID = \"GH_FOLDER_ID\";|const FOLDER_ID = '${{ secrets.GH_FOLDER_ID }}';|g" index.html
          sed -i "s|const GITHUB_USERNAME = \"GH_GITHUB_USERNAME\";|const GITHUB_USERNAME = '${{ secrets.GH_GITHUB_USERNAME }}';|g" index.html
          sed -i "s|const PAT = \"GH_PAT\";|const PAT = '${{ secrets.GH_PAT }}';|g" index.html
          sed -i "s|const PHOTOS_METADATA_FILE_PATH = \"GH_PHOTOS_METADATA_FILE_PATH\";|const PHOTOS_METADATA_FILE_PATH = '${{ secrets.GH_PHOTOS_METADATA_FILE_PATH }}';|g" index.html
          sed -i "s|const REPO_NAME = \"GH_REPO_NAME\";|const REPO_NAME = '${{ secrets.GH_REPO_NAME }}';|g" index.html
