name: Inject Secrets Into HTML

on:
  push:
    branches: [main]

jobs:
  inject-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Inject secrets into HTML
        run: |
          sed -i "s|const GITHUB_USERNAME = 'REPLACE_ME';|const GITHUB_USERNAME = '${{ secrets.GH_GITHUB_USERNAME }}';|g" index.html
          sed -i "s|const REPO_NAME = 'REPLACE_ME';|const REPO_NAME = '${{ secrets.GH_REPO_NAME }}';|g" index.html
          sed -i "s|const PAT = 'REPLACE_ME';|const PAT = '${{ secrets.GH_PAT }}';|g" index.html
          sed -i "s|const FILE_PATH = 'REPLACE_ME';|const FILE_PATH = '${{ secrets.GH_FILE_PATH }}';|g" index.html
          sed -i "s|const COMMENTS_FILE_PATH = 'REPLACE_ME';|const COMMENTS_FILE_PATH = '${{ secrets.GH_COMMENTS_FILE_PATH }}';|g" index.html
          sed -i "s|const PHOTOS_METADATA_FILE_PATH = 'REPLACE_ME';|const PHOTOS_METADATA_FILE_PATH = '${{ secrets.GH_PHOTOS_METADATA_FILE_PATH }}';|g" index.html
          sed -i "s|const LOGS_FILE_PATH = 'REPLACE_ME';|const LOGS_FILE_PATH = '${{ secrets.GH_LOGS_FILE_PATH }}';|g" index.html
          sed -i "s|const FOLDER_ID = 'REPLACE_ME';|const FOLDER_ID = '${{ secrets.GH_FOLDER_ID }}';|g" index.html
          sed -i "s|const API_KEY = 'REPLACE_ME';|const API_KEY = '${{ secrets.GH_API_KEY }}';|g" index.html

      - name: Debug index.html
        run: cat index.html
