name: Build & Inject Secrets

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Inject secrets into main.js
      - name: Inject secrets into JS
        run: |
          sed -i "s|const API_KEY = 'REPLACE_ME';|const API_KEY = '${{ secrets.GH_API_KEY }}';|g" main.js
          sed -i "s|const FILE_PATH = 'REPLACE_ME';|const FILE_PATH = '${{ secrets.GH_FILE_PATH }}';|g" main.js
          sed -i "s|const FOLDER_ID = 'REPLACE_ME';|const FOLDER_ID = '${{ secrets.GH_FOLDER_ID }}';|g" main.js
          sed -i "s|const GITHUB_USERNAME = 'REPLACE_ME';|const GITHUB_USERNAME = '${{ secrets.GH_GITHUB_USERNAME }}';|g" main.js
          sed -i "s|const PAT = 'REPLACE_ME';|const PAT = '${{ secrets.GH_PAT }}';|g" main.js
          sed -i "s|const PHOTOS_METADATA_FILE_PATH = 'REPLACE_ME';|const PHOTOS_METADATA_FILE_PATH = '${{ secrets.GH_PHOTOS_METADATA_FILE_PATH }}';|g" main.js
          sed -i "s|const REPO_NAME = 'REPLACE_ME';|const REPO_NAME = '${{ secrets.GH_REPO_NAME }}';|g" main.js
